name: MyPortals
main: cl.netgamer.myportals.MyPortals
version: 18

commands:
  portal:
    description: implements user created portals.
    usage: "/portal: show available subcommands"
    aliases: [p]

# aqui tambien se configuran los permisos
# no usar la letra enye
