name: MyPortals
main: cl.netgamer.myportals.MyPortals
version: 15

commands:
   portal:
      description: implements teleporting trougth user created portals
      usage: "/portal: currently MyPortals is disabled"
      #permission: <plugin name>.basic
      #permission-message: You don't have <permission>

# aqui tambien se configuran los permisos
# no usar la letra enye
